# Generated by Django 4.1 on 2022-08-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_next_post_post_previous_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='overview',
            field=models.CharField(max_length=500),
        ),
    ]
